stages:
  - main

#
# deploy
deploy:
  stage: main
  image: maven:3.6.3-jdk-8
  script:
    - GPG_FILE=`find / -name xuxiaowei_0x97A36125_SECRET`
    - echo $GPG_FILE
    - gpg --import $GPG_FILE
    - SETTINGS_FILE=`find / -name settings.xml`
    - echo $SETTINGS_FILE
    - sed -i "s#</servers>#<server><id>ossrh</id><username>$ossrh_user</username><password>$ossrh_pass</password></server>&#" $SETTINGS_FILE
    - git --version
    - NAME=`mvn help:evaluate -Dexpression=project.name -q -DforceStdout`
    - VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`
    - PACKAGING=`mvn help:evaluate -Dexpression=project.packaging -q -DforceStdout`
    - echo 名称：$NAME
    - echo 版本：$VERSION
    - echo 包：$PACKAGING
    - echo 常量网址：https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - echo 当前分支：$CI_COMMIT_BRANCH
    - echo 主分支：$CI_DEFAULT_BRANCH
    - echo 项目路径：$CI_PROJECT_DIR
    - mvn clean -U package source:jar javadoc:jar deploy -DskipTests && echo 发布完成
  artifacts:
    paths:
      - target/spring-boot-starter-webchat-miniprogram-*
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
